title: Another trench
#author:
#  name: 
#  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  Just another blog.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    - { platform: youtube, user_url: "https://www.youtube.com/afknah" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#remote_theme: jekyll/minima
remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true
