theme: minima
title: "Firrens Bravader"

header_pages:
  - index.md
  - about.md
  
minima:
  social_links:
    - { platform: youtube,  user_url: "https://www.youtube.com/channel/UC-TP8W4evIORnLL49OQk9iQ" }
