title: Another ditch
author:
  name: David Johansson
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  Just another useless blog.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: youtube,        user_url: "https://www.youtube.com/afknah" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-seo-tag
